### ISSUE TITLE
'logout' over ssh doesn't end ssh connection

### ISSUE THREAD

**Issue by dbittman** [jmolloy/pedigree#12]
Typing 'logout' or ctrl-d keeps the connection alive, you can still type, but nothing happens.

**Comment by miselin** [comment]
This is a regression somewhere, this has worked in the past.

**Comment by miselin** [comment]
This is a race condition where:
1. Process begins terminating, sending SIGCHLD to parent.
2. Parent handles SIGCHLD by calling waitpid() with WNOHANG.
3. Parent returns without reaping any PIDs.
4. Process completes termination, is now ready to be reaped.

**Comment by miselin** [comment]
This is now fixed.
