### ISSUE TITLE
seq doesn't work

### ISSUE THREAD

**Issue by dbittman** [jmolloy/pedigree#14]
Running seq with no arguments causes a segfault, running with a numeric argument results in no output.

**Comment by miselin** [comment]
Running without arguments should now be fixed. Working on the numeric arguments issue.

**Comment by miselin** [comment]
FWIW, when running locally (not over SSH), `seq 1 2 3` just outputs '0' over and over and over again.

**Comment by miselin** [comment]
This should now be solved.
