### ISSUE TITLE
Lots of console output causes ssh session to freeze

### ISSUE THREAD

**Issue by dbittman** [jmolloy/pedigree#18]
I ran 'yes' on one connection, and was then unable to type into the session (ctrl-c didn't work), but I was able to log in on a new ssh connection.

**Comment by miselin** [comment]
Same cause as #9 I believe.

**Comment by miselin** [comment]
This should now be resolved. The online SSH session is not currently up, but I was able to reproduce the problem without using SSH (and therefore check that it is fixed).

Thanks for reporting! :)
