### ISSUE TITLE
Trying to run a shell script using ./ results in the DynamicLinker trying to run the script

### ISSUE THREAD

**Issue by lsproc** [jmolloy/pedigree#5]
If you try to execute a shell script (such as a configure script), or even a non shell script such as a C code file, then the DynamicLinker will try to execute the file and crash and burn as you would expect.

When executing a code file: breakpoint as it knows it aint an ELF.
When executing a shell script: pagefault

**Comment by jmolloy** [comment]
Known issue - fix is to add shebang parsing to the posix_execve function. Leaving open, needs fixing.

**Comment by miselin** [comment]
This was fixed forever ago, making a note here now.
