### ISSUE TITLE
Since http://pedigree-project.org/ is down, pup can't get required dependencies, code can't be built.

### ISSUE THREAD

**Issue by ghost** [jmolloy/pedigree#6]
The build scripts rely on http://pedigree-project.org/ existing and providing extra libraries required to build this code. Since this site is down, the code can't be built.

May I suggest that _all_ the required dependencies be provided on GitHub?

**Comment by miselin** [comment]
Thanks for reporting this.

I am aware of this, and currently working on sorting this out. I've been busy with a few other things but will hopefully have something worked out for this soon.

Ideally, it would be possible to detect some of the libraries are not present and fall back to the text-only user interface (which, while 'bash' would not be present, at least allows code to be built and hacked on). This would be a matter of detecting, say, Cairo is missing in `SConstruct`, and forcing the `nogfx` build option to True if it is. Then, we'd need to checks for whether to build `TUI`, `winman`, etc, based on the `nogfx` variable.

So there's a few options, but getting the proper repository back up and running online is currently the main priority.

**Comment by miselin** [comment]
http://pup.pedigree-project.org is alive again and has the required set of x86_64 packages.

Please make sure you run `easy_build_x64.sh` rather than `easy_build_x86.sh` as the latter script will shortly be phased out.

Also, ensure you are on the `develop` branch to ensure you are using the latest code.

**Comment by miselin** [comment]
Closing this, I have done a few fully-clean builds and determined the build is doable.
